/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "tests.check" instead.
 */

#include <check.h>

#include <stdio.h>
#include <stdlib.h>
#include <math.h>

#include "c/s21_SmartCalc_v1.0.h"

START_TEST(simpleOperations)
{
double res = 0;
int error = 0;
double origin = 5+4;
res = calculation("5+4","",&error);
ck_assert_double_eq_tol(origin, res, 1e-7);
ck_assert_int_eq(error, 0);

origin = -7-4;
res = calculation("-7-4","",&error);
ck_assert_double_eq_tol(origin, res, 1e-7);
ck_assert_int_eq(error, 0);

origin = 6*2;
res = calculation("6*2","",&error);
ck_assert_double_eq_tol(origin, res, 1e-7);
ck_assert_int_eq(error, 0);

origin = 2.5;
res = calculation("10/4","",&error);
ck_assert_double_eq_tol(origin, res, 1e-7);
ck_assert_int_eq(error, 0);

origin = -60+74;
res = calculation("-60+74","",&error);
ck_assert_double_eq_tol(origin, res, 1e-7);
ck_assert_int_eq(error, 0);

origin = -1;
res = calculation("-(2+2)/4","",&error);
ck_assert_double_eq_tol(origin, res, 1e-7);
ck_assert_int_eq(error, 0);

origin = pow(2,3);
res = calculation("2^3","",&error);
ck_assert_double_eq_tol(origin, res, 1e-7);
ck_assert_int_eq(error, 0);

origin = -1;
res = calculation("-1","",&error);
ck_assert_double_eq_tol(origin, res, 1e-7);
ck_assert_int_eq(error, 0);

origin = 1;
res = calculation("+1","",&error);
ck_assert_double_eq_tol(origin, res, 1e-7);
ck_assert_int_eq(error, 0);

origin = 10%5;
res = calculation("10mod5","",&error);
ck_assert_double_eq_tol(origin, res, 1e-7);
ck_assert_int_eq(error, 0);

origin = 5%10;
res = calculation("5mod10","",&error);
ck_assert_double_eq_tol(origin, res, 1e-7);
ck_assert_int_eq(error, 0);

origin = sqrt(4);
res = calculation("sqrt(4)","",&error);
ck_assert_double_eq_tol(origin, res, 1e-7);
ck_assert_int_eq(error, 0);

origin = sqrt(-4);
res = calculation("sqrt(-4)","",&error);
ck_assert_double_nan(res);
ck_assert_int_eq(error, 0);

origin = INFINITY;
res = calculation("10/0","",&error);
ck_assert_double_infinite(res);
ck_assert_int_eq(error, 0);

origin = 10*0;
res = calculation("10*0","",&error);
ck_assert_double_eq_tol(origin, res, 1e-7);
ck_assert_int_eq(error, 0);

origin = 123 + 0.456;
res = calculation("123+0.456","",&error);
ck_assert_double_eq_tol(origin, res, 1e-7);
ck_assert_int_eq(error, 0);

}
END_TEST

START_TEST(functions)
{
double res = 0;
int error = 0;
double origin = sin(30);
res = calculation("sin(30)","",&error);
ck_assert_double_eq_tol(origin, res, 1e-7);
ck_assert_int_eq(error, 0);

origin = cos(30);
res = calculation("cos(30)","",&error);
ck_assert_double_eq_tol(origin, res, 1e-7);
ck_assert_int_eq(error, 0);

origin = tan(30);
res = calculation("tan(30)","",&error);
ck_assert_double_eq_tol(origin, res, 1e-7);
ck_assert_int_eq(error, 0);

origin = asin(30);
res = calculation("asin(30)","",&error);
ck_assert_double_nan(res);
ck_assert_int_eq(error, 0);

origin = acos(30);
res = calculation("acos(30)","",&error);
ck_assert_double_nan(res);
ck_assert_int_eq(error, 0);

origin = atan(30);
res = calculation("atan(30)","",&error);
ck_assert_double_eq_tol(origin, res, 1e-7);
ck_assert_int_eq(error, 0);

origin = log(10);
res = calculation("ln(10)","",&error);
ck_assert_double_eq_tol(origin, res, 1e-7);
ck_assert_int_eq(error, 0);

origin = log10(10);
res = calculation("log(10)","",&error);
ck_assert_double_eq_tol(origin, res, 1e-7);
ck_assert_int_eq(error, 0);

}
END_TEST

START_TEST(bigExpressions)
{
double res = 0;
int error = 0;
double origin = INFINITY;
double X = 2;
res = calculation("4^acos(X/4)/tan(2*X)","0",&error);
ck_assert_double_infinite(res);
ck_assert_int_eq(error, 0);

origin = pow(4, acos(X / 4)) / tan(2 * X);
res = calculation("4^acos(X/4)/tan(2*X)","2",&error);
ck_assert_double_eq_tol(origin, res, 1e-7);
ck_assert_int_eq(error, 0);

origin = -0.58934793341;
res = calculation("(4^acos(2/4)/tan(2*2)/(5^acos(2/4))/tan(tan(tan(2*2))))","",&error);
ck_assert_double_eq_tol(origin, res, 1e-7);
ck_assert_int_eq(error, 0);

origin = 4;
res = calculation("(((((((2+2)))))))","",&error);
ck_assert_double_eq_tol(origin, res, 1e-7);
ck_assert_int_eq(error, 0);

origin = 1.15782128235;
res = calculation("tan(2*2)","",&error);
ck_assert_double_eq_tol(origin, res, 1e-7);
ck_assert_int_eq(error, 0);

origin = 6.268113;
res = calculation("1+2*3^sin(0.4)^3*2+1","",&error);
ck_assert_double_eq_tol(origin, res, 1e-7);
ck_assert_int_eq(error, 0);

origin = 1.0417824;
res = calculation("2^sin(0.4)^3","",&error);
ck_assert_double_eq_tol(origin, res, 1e-7);
ck_assert_int_eq(error, 0);

origin = 4.5;
res = calculation("81/3^2/2","",&error);
ck_assert_double_eq_tol(origin, res, 1e-7);
ck_assert_int_eq(error, 0);

origin = 1.59353092682;
res = calculation("acos(-0.5)+asin(-0.5)+atan(0.1)*cos(30)*sin(20)*tan(45)","",&error);
ck_assert_double_eq_tol(origin, res, 1e-7);
ck_assert_int_eq(error, 0);

origin = 1.59191793818660;
res = calculation("-(cos(20)-10)mod2","",&error);
ck_assert_double_eq_tol(origin, res, 1e-7);
ck_assert_int_eq(error, 0);

origin = 0.0016;
res = calculation("(-5)^(-4)","",&error);
ck_assert_double_eq_tol(origin, res, 1e-7);
ck_assert_int_eq(error, 0);

origin = 120;
res = calculation("+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+"
      "1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+"
      "1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+"
      "1+1+1+1+1+1+1+1+1+1+1+1+1","",&error);
ck_assert_double_eq_tol(origin, res, 1e-7);
ck_assert_int_eq(error, 0);

}
END_TEST

START_TEST(errors)
{
//double res = 0;
int error = 0;
//double origin = 5+4;
calculation("5+*4","",&error);
ck_assert_int_ne(error, 0);

calculation("(2+2)))))))","",&error);
ck_assert_int_ne(error, 0);

calculation("(((((((2+2))","",&error);
ck_assert_int_ne(error, 0);

calculation("1+/3","",&error);
ck_assert_int_ne(error, 0);

calculation("-----2","",&error);
ck_assert_int_ne(error, 0);

calculation("2*/3","",&error);
ck_assert_int_ne(error, 0);

calculation("/4","",&error);
ck_assert_int_ne(error, 0);

calculation("9+sin()+1","",&error);
ck_assert_int_ne(error, 0);

calculation("12..4+4","",&error);
ck_assert_int_ne(error, 0);

calculation("(*4+2)","",&error);
ck_assert_int_ne(error, 0);

calculation(".4+4","",&error);
ck_assert_int_ne(error, 0);

calculation("06+9","",&error);
ck_assert_int_ne(error, 0);

calculation("6+09","",&error);
ck_assert_int_ne(error, 0);
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, simpleOperations);
    tcase_add_test(tc1_1, functions);
    tcase_add_test(tc1_1, bigExpressions);
    tcase_add_test(tc1_1, errors);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
